stages:
  - test
  - build

test:
  image: microsoft/dotnet:latest
  stage: test
  script:
    - dotnet test ./Tests/Tests.fsproj

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_TOKEN" $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
