stages:
  - build
  - test
  - publish

build:
  image: microsoft/dotnet:latest
  stage: build
  script:
    - dotnet build ./Server/Server.fsproj

unit:
  image: microsoft/dotnet:latest
  stage: test
  script:
    - dotnet test ./Tests/UnitTests/UnitTests.fsproj
    
integration:
  image: microsoft/dotnet:latest
  stage: test
  script:
    - dotnet build ./Server/Server.fsproj
    - dotnet run -p ./Server/Server.fsproj &
    - dotnet test ./Tests/IntegrationTests/IntegrationTests.fsproj

publish:
  image: docker:latest
  services:
    - docker:dind
  stage: publish
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_TOKEN" $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
