# Official docker image.
image: docker:latest

services:
  - docker:dind

test:
  stage: test
  script:
    - dotnet test .\Tests\Tests.fsproj

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_TOKEN" $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
