# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - echo "$KEYFILE" >> "$HOME/keyfile.json"
  - docker login -u _json_key --password-stdin $REGISTRY < "$HOME/keyfile.json"

build:
  stage: build
  script:
    - docker build --pull -t $REGISTRY_IMAGE .
    - docker push $REGISTRY_IMAGE
  only:
    - master
