# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u _json_key --password-stdin $REGISTRY < "$KEYFILE"

build:
  stage: build
  script:
    - docker build --pull -t $REGISTRY_IMAGE .
    - docker push $REGISTRY_IMAGE
  only:
    - master
