# for local development
version: '3.7'

services:

  server:
    build: ./Server
    ports:
      - '80:8080'
    volumes:
      - '.:/app'
    working_dir: '/app/Server'
    command: 'dotnet watch run'

  client:
    build: ./Client
    ports:
      - '8080:8080'
    volumes:
      - './Client:/app/Client'
    working_dir: '/app/Client'
    command: 'npm run serve'
