version: '3.7'

services:

  db:
    image: mongo
    volumes:
      - mongodata:/data/db

  app:
    environment:
      NODE_ENV: staging
      DB_URL: mongodb://db:27017/
      #DB_URL: mongodb://root:abc123@ds123624.mlab.com:23624
      DB_NAME: ConsiliumDb
      SERVER_URL: http://localhost:80
    ports:
      - '80:80'
    build:
      context: ../
      dockerfile: .docker/staging.dockerfile

volumes:
  mongodata:
